# Generated by Django 4.2.17 on 2024-12-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_user_is_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='tutorprofile',
            name='specializations',
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='languages',
            field=models.TextField(blank=True, help_text='Programming languages this tutor can teach.'),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='specializations',
            field=models.TextField(blank=True, help_text='Advanced areas this tutor can teach.'),
        ),
    ]
