# Generated by Django 4.2.17 on 2024-12-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_remove_tutorprofile_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='requested_start_date',
            field=models.DateField(help_text='Preferred start date for the lesson', null=True),
        ),
    ]
