# Generated by Django 4.2.17 on 2024-12-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_lessonrequest_requested_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonrequest',
            name='requested_languages',
        ),
        migrations.RemoveField(
            model_name='lessonrequest',
            name='requested_specializations',
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='requested_languages',
            field=models.TextField(blank=True, help_text='Programming languages the student wants to learn.'),
        ),
        migrations.AddField(
            model_name='lessonrequest',
            name='requested_specializations',
            field=models.TextField(blank=True, help_text='Advanced topics the student wants to focus on.'),
        ),
    ]
