# Generated by Django 4.2.17 on 2024-12-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_remove_lessonrequest_requested_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequest',
            name='tutor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requests', to='tutorials.tutorprofile'),
        ),
    ]
